{
 "title": "Payment Service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(up{service=\"session-prometheus\"}, pod)"
   },
   {
    "name": "bank",
    "label": "Bank Type",
    "query": "label_values(session_prom_pay_requests_active{pod=~\"$pod\"}, bank_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Payment Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "TL" }
   ],
   "targets": [
    {
     "expr": "sum(increase(session_prom_payment_value_tl_sum{pod=~\"$pod\"}[1m])) by (pod) / sum(increase(session_prom_payment_value_tl_count{pod=~\"$pod\"}[1m])) by (pod) OR vector(0)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Payment Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "session_prom_payment_duration_seconds{pod=~\"$pod\", bank_type=~\"$bank\"}",
     "legendFormat": "{{ pod }} {{ quantile }}"
    }
   ]
  },
  {
   "title": "Payment Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(session_prom_payment_value_tl_count{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Payment Rate With Recorded Card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(session_prom_payment_with_recorded_card_total{pod=~\"$pod\"}[1m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(session_prom_pay_requests_active{bank_type=~\"$bank_type\"}) OR vector(0)"
    }
   ]
  }
 ]
}